export default [
    {
      id: 1,
      username: '@greatsanchez',
      socialNetwork: 'facebook',
      icon: { url: 'images/icon-facebook.svg', name: 'Facebook' },
      total: 9487,
      description: 'Followers',
      totalToday: 48,
    },
    {
      id: 2,
      username: '@greatsanchez',
      socialNetwork: 'twitter',
      icon: { url: 'images/icon-twitter.svg', name: 'Twitter' },
      total: 9247,
      description: 'Followers',
      totalToday: 84,
    },
    {
      id: 3,
      username: '@greatsanchez',
      socialNetwork: 'instagram',
      icon: { url: 'images/icon-instagram.svg', name: 'Instagram' },
      total: 94647,
      description: 'Followers',
      totalToday: 9274,
    },
    {
      id: 4,
      username: '@greatsanchez',
      socialNetwork: 'youtube',
      icon: { url: 'images/icon-youtube.svg', name: 'Youtube' },
      total: 2638,
      description: 'Subscribers',
      totalToday: -857,
    },
  ]