export default [
    {
      id: 1,
      username: '@Profilesanchez',
      socialNetwork: 'facebook',
      icon: { url: 'images/icon-facebook.svg', name: 'Facebook' },
      total: 7868,
      description: 'Followers',
      totalToday: 75,
    },
    {
      id: 2,
      username: '@Profilesanchez',
      socialNetwork: 'twitter',
      icon: { url: 'images/icon-twitter.svg', name: 'Twitter' },
      total: 3296,
      description: 'Followers',
      totalToday: 49,
    },
    {
      id: 3,
      username: '@Profilesanchez',
      socialNetwork: 'instagram',
      icon: { url: 'images/icon-instagram.svg', name: 'Instagram' },
      total: 8763,
      description: 'Followers',
      totalToday: 9576,
    },
    {
      id: 4,
      username: '@Profilesanchez',
      socialNetwork: 'youtube',
      icon: { url: 'images/icon-youtube.svg', name: 'Youtube' },
      total: 9857,
      description: 'Subscribers',
      totalToday: -234,
    },
  ]